"""Add Photo model

Revision ID: 1ede77ea02cd
Revises: 9b1cfe3cc9e9
Create Date: 2025-04-20 17:40:43.571026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ede77ea02cd'
down_revision = '9b1cfe3cc9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_generated', sa.Boolean(), nullable=True),
    sa.Column('exif_data', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_file_hash'), ['file_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_photo_relative_path'), ['relative_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_photo_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_timestamp'))
        batch_op.drop_index(batch_op.f('ix_photo_relative_path'))
        batch_op.drop_index(batch_op.f('ix_photo_file_hash'))

    op.drop_table('photo')
    # ### end Alembic commands ###
